allowBuilds:
  esbuild: true
  '@clerk/shared': false
  stream-chat: false

minimumReleaseAgeExclude:
  - '@clerk/backend@3.11.2'
  - '@clerk/express@2.1.38'
  - '@clerk/shared@4.25.1'
  - prettier@3.9.5
