name: Dokploy Deployment Status

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trigger & Track Dokploy Deploy
        uses: benbristow/dokploy-deploy-action@0.2.2
        with:
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
          api_token: ${{ secrets.DOKPLOY_TOKEN }}
          application_id: ${{ secrets.DOKPLOY_APP_ID }}
          service_type: application
